export const demoData = {
  floor: [
    { label: 'STAINS', value: 'STAINS' },
    { label: 'BURNS', value: 'BURNS' },
    { label: 'HOLES', value: 'HOLES' },
    { label: 'SANGS', value: 'SANGS' },
    { label: 'WORN', value: 'WORN' },
  ],
  wall: [
    { label: 'HOLES', value: 'HOLES' },
    { label: 'MARKS', value: 'MARKS' },
    { label: 'STAINS', value: 'STAINS' },
    { label: 'HOOKS', value: 'HOOKS' },
    { label: 'NAILS', value: 'NAILS' },
  ],
  celling: [
    { label: 'STAINS', value: 'STAINS' },
    { label: 'HOLES', value: 'HOLES' },
    { label: 'CRACKED_PLASTER', value: 'CRACKED_PLASTER' },
    { label: 'OTHER_DAMAGE', value: 'OTHER_DAMAGE' },
  ],
  door: [
    { label: 'SCRATCHES', value: 'SCRATCHES' },
    { label: 'DISCOLOURED', value: 'DISCOLOURED' },
    { label: 'SECURED', value: 'SECURED' },
  ],
  lighting: [
    { label: 'STAINS', value: 'STAINS' },
    { label: 'RUSTY', value: 'RUSTY' },
    { label: 'BROKEN', value: 'BROKEN' },
  ],
  windows: [
    { label: 'DIRTY', value: 'DIRTY' },
    { label: 'MISSING_LOCKS', value: 'MISSING_LOCKS' },
    { label: 'BROKEN_GLASS_OR_FRAMES', value: 'BROKEN_GLASS_OR_FRAMES' },
  ],
  curtains: [
    { label: 'STAINS', value: 'STAINS' },
    { label: 'HOLES', value: 'HOLES' },
    { label: 'TORN', value: 'TORN' },
  ],
  appliances: [
    { label: 'DIRTY', value: 'DIRTY' },
    { label: 'DAMAGED', value: 'DAMAGED' },
    { label: 'INOPERABLE', value: 'INOPERABLE' },
    {
      label: 'MISSING_OR_HAS_MISSING_PARTS',
      value: 'MISSING_OR_HAS_MISSING_PARTS',
    },
  ],
  default: [
    { label: 'SCRATCHES', value: 'SCRATCHES' },
    { label: 'BURNS', value: 'BURNS' },
    { label: 'UPHOLSTRY_WORN', value: 'UPHOLSTRY_WORN' },
    {
      label: 'MISSING_OR_HAS_MISSING_PARTS',
      value: 'MISSING_OR_HAS_MISSING_PARTS',
    },
  ],
  occupire_id_type: [
    { label: 'NRIC', value: 'NRIC' },
    { label: 'Employment Pass', value: 'Employment Pass' },
    { label: 'Work Permit', value: 'Work Permit' },
    { label: 'Student Pass', value: 'Student Pass' },
  ],
  rules: [
    { label: 'Applicable', value: 'Applicable' },
    { label: 'Not Application', value: 'Not Application' },
  ],
  furnishing_status: [
    { label: 'unfurnished', value: 'unfurnished' },
    { label: 'partial', value: 'partial' },
    { label: 'Fully', value: 'Fully' },
  ],
  id_type: [
    { label: 'NRIC No', value: 'NRIC No' },
    { label: 'Passport No', value: 'Passport No' },
    { label: 'FIN', value: 'FIN' },
    { label: 'UEN', value: 'UEN' },
  ],
  MRT: [
    { label: 'ADMIRALTY', value: 'ADMIRALTY' },
    { label: 'ALJUNIED', value: 'ALJUNIED' },
    { label: 'ANG MO KIO', value: 'ANG MO KIO' },
    { label: 'BARTLEY', value: 'BARTLEY' },
    { label: 'BAYFRONT', value: 'BAYFRONT' },
    { label: 'BEDOK', value: 'BEDOK' },
    { label: 'BISHAN', value: 'BISHAN' },
    { label: 'BOON KENG', value: 'BOON KENG' },
    { label: 'BOON LAY', value: 'BOON LAY' },
    { label: 'BOTANIC GARDENS', value: 'BOTANIC GARDENS' },
    { label: 'BRADDELL', value: 'BRADDELL' },
    { label: 'BRAS BASAH', value: 'BRAS BASAH' },
    { label: 'BUANGKOK', value: 'BUANGKOK' },
    { label: 'BUGIS', value: 'BUGIS' },
    { label: 'BUKIT BATOK', value: 'BUKIT BATOK' },
    { label: 'BUKIT GOMBAK', value: 'BUKIT GOMBAK' },
    { label: 'BUONA VISTA', value: 'BUONA VISTA' },
    { label: 'CALDECOTT', value: 'CALDECOTT' },
    { label: 'CHANGI AIRPORT', value: 'CHANGI AIRPORT' },
    { label: 'CHINATOWN', value: 'CHINATOWN' },
    { label: 'CHINESE GARDEN', value: 'CHINESE GARDEN' },
    { label: 'CHOA CHU KANG', value: 'CHOA CHU KANG' },
    { label: 'CITY HALL', value: 'CITY HALL' },
    { label: 'CLARKE QUAY', value: 'CLARKE QUAY' },
    { label: 'CLEMENTI', value: 'CLEMENTI' },
    { label: 'COMMONWEALTH', value: 'COMMONWEALTH' },
    { label: 'DAKOTA', value: 'DAKOTA' },
    { label: 'DHOBY GHAUT', value: 'DHOBY GHAUT' },
    { label: 'DOVER', value: 'DOVER' },
    { label: 'DOWNTOWN', value: 'DOWNTOWN' },
    { label: 'ESPLANADE', value: 'ESPLANADE' },
    { label: 'EUNOS', value: 'EUNOS' },
    { label: 'EXPO', value: 'EXPO' },
    { label: 'FARRER PARK', value: 'FARRER PARK' },
    { label: 'FARRER ROAD', value: 'FARRER ROAD' },
    { label: 'HARBOURFRONT', value: 'HARBOURFRONT' },
    { label: 'HAW PAR VILLA', value: 'HAW PAR VILLA' },
    { label: 'HOLLAND VILLAGE', value: 'HOLLAND VILLAGE' },
    { label: 'HOUGANG', value: 'HOUGANG' },
    { label: 'JOO KOON', value: 'JOO KOON' },
    { label: 'JURONG EAST', value: 'JURONG EAST' },
    { label: 'KALLANG', value: 'KALLANG' },
    { label: 'KEMBANGAN', value: 'KEMBANGAN' },
    { label: 'KENT RIDGE', value: 'KENT RIDGE' },
    { label: 'KHATIB', value: 'KHATIB' },
    { label: 'KOVAN', value: 'KOVAN' },
    { label: 'KRANJI', value: 'KRANJI' },
    { label: 'LABRADOR PARK', value: 'LABRADOR PARK' },
    { label: 'LAKESIDE', value: 'LAKESIDE' },
    { label: 'LAVENDER', value: 'LAVENDER' },
    { label: 'LITTLE INDIA', value: 'LITTLE INDIA' },
    { label: 'LORONG CHUAN', value: 'LORONG CHUAN' },
    { label: 'MACPHERSON', value: 'MACPHERSON' },
    { label: 'MARINA BAY', value: 'MARINA BAY' },
    { label: 'MARINA SOUTH PIER', value: 'MARINA SOUTH PIER' },
    { label: 'MARSILING', value: 'MARSILING' },
    { label: 'MARYMOUNT', value: 'MARYMOUNT' },
    { label: 'MOUNTBATTEN', value: 'MOUNTBATTEN' },
    { label: 'NEWTON', value: 'NEWTON' },
    { label: 'NICOLL HIGHWAY', value: 'NICOLL HIGHWAY' },
    { label: 'NOVENA', value: 'NOVENA' },
    { label: 'ONE-NORTH', value: 'ONE-NORTH' },
    { label: 'ORCHARD', value: 'ORCHARD' },
    { label: 'OUTRAM PARK', value: 'OUTRAM PARK' },
    { label: 'PASIR PANJANG', value: 'PASIR PANJANG' },
    { label: 'PASIR RIS', value: 'PASIR RIS' },
    { label: 'PAYA LEBAR', value: 'PAYA LEBAR' },
    { label: 'PIONEER', value: 'PIONEER' },
    { label: 'POTONG PASIR', value: 'POTONG PASIR' },
    { label: 'PROMENADE', value: 'PROMENADE' },
    { label: 'PUNGGOL', value: 'PUNGGOL' },
    { label: 'QUEENSTOWN', value: 'QUEENSTOWN' },
    { label: 'RAFFLES PLACE', value: 'RAFFLES PLACE' },
    { label: 'REDHILL', value: 'REDHILL' },
    { label: 'SEMBAWANG', value: 'SEMBAWANG' },
    { label: 'SENGKANG', value: 'SENGKANG' },
    { label: 'SERANGOON', value: 'SERANGOON' },
    { label: 'SIMEI', value: 'SIMEI' },
    { label: 'SOMERSET', value: 'SOMERSET' },
    { label: 'STADIUM', value: 'STADIUM' },
    { label: 'TAI SENG', value: 'TAI SENG' },
    { label: 'TAMPINES', value: 'TAMPINES' },
    { label: 'TANAH MERAH', value: 'TANAH MERAH' },
    { label: 'TANJONG PAGAR', value: 'TANJONG PAGAR' },
    { label: 'TELOK AYER', value: 'TELOK AYER' },
    { label: 'TELOK BLANGAH', value: 'TELOK BLANGAH' },
    { label: 'TIONG BAHRU', value: 'TIONG BAHRU' },
    { label: 'TOA PAYOH', value: 'TOA PAYOH' },
    { label: 'WOODLANDS', value: 'WOODLANDS' },
    { label: 'WOODLEIGH', value: 'WOODLEIGH' },
    { label: 'YEW TEE', value: 'YEW TEE' },
    { label: 'YIO CHU KANG', value: 'YIO CHU KANG' },
  ],
  districtName: [
    { label: 'All of Singapore', value: 'All of Singapore' },
    {
      label: 'D01 Boat Quay / Raffles Place / Marina',
      value: 'D01 Boat Quay / Raffles Place / Marina',
    },
    {
      label: 'D02 Chinatown / Tanjong Pagar ',
      value: 'D02 Chinatown / Tanjong Pagar',
    },
    {
      label: 'D03 Alexandra / Commonwealth',
      value: 'D03 Alexandra / Commonwealth',
    },
    {
      label: 'D04 Harbourfront / Telok Blangah',
      value: 'D04 Harbourfront / Telok Blangah',
    },
    {
      label: 'D05 Buona Vista / West Coast / Clementi New Town',
      value: 'D05 Buona Vista / West Coast / Clementi New Town',
    },
    {
      label: 'D06 City Hall / Clarke Quay',
      value: 'D06 City Hall / Clarke Quay',
    },
    {
      label: 'D07 Beach Road / Bugis/ Rochor',
      value: 'D07 Beach Road / Bugis/ Rochor',
    },
    {
      label: 'D08 Farrer Park / Serangoon',
      value: 'D08 Farrer Park / Serangoon',
    },
    {
      label: 'D09 Orchard / River Valley',
      value: 'D09 Orchard / River Valley',
    },
    {
      label: 'D10 Tanglin / Holland / Bukit Timah',
      value: 'D10 Tanglin / Holland / Bukit Timah',
    },
    { label: 'D11 Newton / Novena', value: 'D11 Newton / Novena' },
    { label: 'D12 Balestier / Toa Payoh', value: 'D12 Balestier / Toa Payoh' },
    {
      label: 'D13 Macpherson / Potong Pasir',
      value: 'D13 Macpherson / Potong Pasir',
    },
    {
      label: 'D14 Eunos / Geylang / Paya Lebar',
      value: 'D14 Eunos / Geylang / Paya Lebar',
    },
    {
      label: 'D15 East Coast / Marina Parade',
      value: 'D15 East Coast / Marina Parade',
    },
    {
      label: 'D16 Bedok / Upper East Coast',
      value: 'D16 Bedok / Upper East Coast',
    },
    {
      label: 'D17 Changi Airport / Changi Village',
      value: 'D17 Changi Airport / Changi Village',
    },
    { label: 'D18 Pasir Ris / Tampines', value: 'D18 Pasir Ris / Tampines' },
    {
      label: 'D19 Hougang / Punggol / Sengkang',
      value: 'D19 Hougang / Punggol / Sengkang',
    },
    {
      label: 'D20 Ang Mo Kio / Bishan / Thomson',
      value: 'D20 Ang Mo Kio / Bishan / Thomson',
    },
    {
      label: 'D21 Clementi Park / Upper Bukit Timah',
      value: 'D21 Clementi Park / Upper Bukit Timah',
    },
    {
      label: 'D22 Boon Lay / Jurong / Tuas',
      value: 'D22 Boon Lay / Jurong / Tuas',
    },
    {
      label: 'D23 Diary Farm / Bukit Panjang / Choa Chu Kang',
      value: 'D23 Diary Farm / Bukit Panjang / Choa Chu Kang',
    },
    { label: 'D24 Lim Chu Kang / Tengah', value: 'D24 Lim Chu Kang / Tengah' },
    { label: 'D25 Admiralty / Woodlands', value: 'D25 Admiralty / Woodlands' },
    {
      label: 'D26 Mandai / Upper Thomson',
      value: 'D26 Mandai / Upper Thomson',
    },
    { label: 'D27 Sembawang / Yishun', value: 'D27 Sembawang / Yishun' },
    {
      label: 'D28 Seletar / Yio Chu Kang',
      value: 'D28 Seletar / Yio Chu Kang',
    },
  ],

  districtNameNew: [
    // { label: 'All of Singapore', value: 'All of Singapore' },
    {
      label: 'District 01',
      value: 'Boat Quay, Chinatown, Havelock Road, Marina Square, Raffles Place, Suntec City',
    },
    {
      label: 'District 02',
      value: 'Anson Road, Chinatown, Neil Road, Raffles Place, Shenton Way, Tanjong Pagar',
    },
    {
      label: 'District 03',
      value: 'Alexandra Road, Tiong Bahru, Queenstown',
    },
    {
      label: 'District 04',
      value: 'Keppel, Mount Faber, Sentosa, Telok Blangah',
    },
    {
      label: 'District 05 ',
      value: 'Buona Vista, Dover, Pasir Panjang, West Coast',
    },
    {
      label: 'District 06 ',
      value: 'City Hall, High Street, North Bridge Road',
    },
    {
      label: 'District 07 ',
      value: 'Beach Road, Bencoolen Road, Bugis, Rochor',
    },
    {
      label: 'District 08 ',
      value: 'Little India, Farrer Park, Serangoon Road',
    },
    {
      label: 'District 09 ',
      value: 'Cairnhill, Killiney, Leonie Hill, Orchard, Oxley',
    },
    {
      label: 'District 10 ',
      value: 'Balmoral, Bukit Timah, Grange Road, Holland, Orchard Boulevard, River Valley, Tanglin',
    },
    { label: 'District 11 ', value: 'Chancery, Bukit Timah, Dunearn Road, Newton' },
    { label: 'District 12 ', value: 'Balestier, Moulmein, Novena, Toa Payoh' },
    {
      label: 'District 13 ',
      value: 'Potong Pasir, Macpherson',
    },
    {
      label: 'District 14 ',
      value: 'Eunos, Geylang, Kembangan, Paya Lebar',
    },
    {
      label: 'District 15 ',
      value: 'Katong, Marine Parade, Siglap, Tanjong Rhu',
    },
    {
      label: 'District 16 ',
      value: 'Bayshore, Bedok, Chai Chee',
    },
    {
      label: 'District 17 ',
      value: 'Changi, Loyang, Pasir Ris',
    },
    { label: 'District 18 ', value: 'Pasir Ris, Simei, Tampines' },
    {
      label: 'District 19 ',
      value: 'Hougang, Punggol, Sengkang',
    },
    {
      label: 'District 20 ',
      value: 'Ang Mo Kio, Bishan, Braddell Road, Thomson',
    },
    {
      label: 'District 21',
      value: 'Clementi, Upper Bukit Timah, Hume Avenue',
    },
    {
      label: 'District 22 ',
      value: 'Boon Lay, Jurong, Tuas',
    },
    {
      label: 'District 23 ',
      value: 'Bukit Batok, Choa Chu Kang, Hillview Avenue, Upper Bukit Timah',
    },
    { label: 'District 24 ', value: 'Kranji, Lim Chu Kang, Sungei Gedong, Tengah' },
    { label: 'District 25 ', value: 'Admiralty, Woodlands' },
    {
      label: 'District 26 ',
      value: 'Tagore, Yio Chu Kang',
    },
    { label: 'District 27 ', value: 'Admiralty, Sembawang, Yishun' },
    {
      label: 'District 28 ',
      value: 'Seletar, Yio Chu Kang',
    },
  ],

  districtNameWithImage: [
    { label: 'All of Singapore', value: 'All of Singapore' },
    {
      label: 'D01 Boat Quay / Raffles Place / Marina',
      value: 'D01 Boat Quay / Raffles Place / Marina',
      images: 'https://live.staticflickr.com/7392/27717855816_8633575d06_b.jpg',
    },
    {
      label: 'D02 Chinatown / Tanjong Pagar ',
      value: 'D02 Chinatown / Tanjong Pagar',
      images: 'https://esingaporeproperty.sg/wp-content/uploads/2017/08/Sky-Everton-Condo-Tower-675x375.jpg',
    },
    {
      label: 'D03 Alexandra / Commonwealth',
      value: 'D03 Alexandra / Commonwealth',
      images:
        'https://esingaporeproperty.sg/wp-content/uploads/2017/08/Avenue-South-Residences-Mixed-Development-675x375.jpg',
    },
    {
      label: 'D04 Harbourfront / Telok Blangah',
      value: 'D04 Harbourfront / Telok Blangah',
      images:
        'https://ejqczs4xhji.exactdn.com/wp-content/uploads/2021/08/tropika-club-magazine_best-condos-in-harbourfront.png?strip=all&lossy=1&ssl=1',
    },
    {
      label: 'D05 Buona Vista / West Coast / Clementi New Town',
      value: 'D05 Buona Vista / West Coast / Clementi New Town',
      images: 'https://fojorealestate.sg/wp-content/uploads/2019/08/Singapore-beautiful-HD-wallpaper-2560x1600-1.jpg',
    },
    {
      label: 'D06 City Hall / Clarke Quay',
      value: 'D06 City Hall / Clarke Quay',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/91461/M/2062271.jpg',
    },
    {
      label: 'D07 Beach Road / Bugis/ Rochor',
      value: 'D07 Beach Road / Bugis/ Rochor',
      images: 'https://sghomesuites.com/wp-content/uploads/2021/02/midtownmodern-feature-592x444.jpg',
    },
    {
      label: 'D08 Farrer Park / Serangoon',
      value: 'D08 Farrer Park / Serangoon',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/20062//L/47852.jpg',
    },
    {
      label: 'D09 Orchard / River Valley',
      value: 'D09 Orchard / River Valley',
      images: 'https://esingaporeproperty.sg/wp-content/uploads/2018/03/Kopar-Condo-Gymnasium-675x375.jpg',
      popularity: 'High',
    },
    {
      label: 'D10 Tanglin / Holland / Bukit Timah',
      value: 'D10 Tanglin / Holland / Bukit Timah',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/86712/M/2026891.jpg',
    },
    {
      label: 'D11 Newton / Novena',
      value: 'D11 Newton / Novena',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/84632/M/2024341.jpg',
    },
    {
      label: 'D12 Balestier / Toa Payoh',
      value: 'D12 Balestier / Toa Payoh',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/82862/M/2028391.jpg',
    },
    {
      label: 'D13 Macpherson / Potong Pasir',
      value: 'D13 Macpherson / Potong Pasir',
      images: 'https://esingaporeproperty.sg/wp-content/uploads/2018/01/The-Tre-Ver-Condo-River-View-675x375.jpg',
    },
    {
      label: 'D14 Eunos / Geylang / Paya Lebar',
      value: 'D14 Eunos / Geylang / Paya Lebar',
      images:
        'https://www.newcondolaunchonline.com/wp-content/uploads/2020/10/park-place-residences-condo-singapore-570-420-c.jpg',
    },
    {
      label: 'D15 East Coast / Marina Parade',
      value: 'D15 East Coast / Marina Parade',
      images:
        'https://www.newcondolaunchonline.com/wp-content/uploads/2023/02/tembusu-grand-best-new-launch-condo-singapore-facade-1950-900-web-570x420.jpg',
    },
    {
      label: 'D16 Bedok / Upper East Coast',
      value: 'D16 Bedok / Upper East Coast',
      images:
        'https://www.newcondolaunchonline.com/wp-content/uploads/2020/08/grandeur-park-residences-condo-singapore-facade-c.jpg',
    },
    {
      label: 'D17 Changi Airport / Changi Village',
      value: 'D17 Changi Airport / Changi Village',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/81852/M/2043541.jpg',
    },
    {
      label: 'D18 Pasir Ris / Tampines',
      value: 'D18 Pasir Ris / Tampines',
      images:
        'https://pic2.99.co/v3/hF64cBwzVKYxqwnwUjnMQj?width=945&mode=fill&text=Fawaz+Fossil&sampling=lanczos&quality=80&version=1&signature=064c1119c7450bb633f79ee96c9c53b768839e14&height=416',
    },
    {
      label: 'D19 Hougang / Punggol / Sengkang',
      value: 'D19 Hougang / Punggol / Sengkang',
      images: 'https://propertysale.com.sg/wp-content/uploads/2021/07/bartley-vue-525x328.jpeg',
    },
    {
      label: 'D20 Ang Mo Kio / Bishan / Thomson',
      value: 'D20 Ang Mo Kio / Bishan / Thomson',
      images: 'https://esingaporeproperty.sg/wp-content/uploads/2018/04/AMO-Residence-Ang-Mo-Kio-Condo-675x375.jpg',
    },
    {
      label: 'D21 Clementi Park / Upper Bukit Timah',
      value: 'D21 Clementi Park / Upper Bukit Timah',
      images:
        'https://newlaunch.propertygiant.com/wp-content/uploads/2020/12/Ki-Residences-Condo-Entrance-Plaza-525x328.jpg?v=1622705422',
    },
    {
      label: 'D22 Boon Lay / Jurong / Tuas',
      value: 'D22 Boon Lay / Jurong / Tuas',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/32092/M/1351042.jpg',
    },
    {
      label: 'D23 Diary Farm / Bukit Panjang / Choa Chu Kang',
      value: 'D23 Diary Farm / Bukit Panjang / Choa Chu Kang',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/28152/M/1373752.jpg',
    },
    {
      label: 'D24 Lim Chu Kang / Tengah',
      value: 'D24 Lim Chu Kang / Tengah',
      images: 'https://esingaporeproperty.sg/wp-content/uploads/2018/04/Copen-Grand-Executive-Condominium.jpeg',
    },
    {
      label: 'D25 Admiralty / Woodlands',
      value: 'D25 Admiralty / Woodlands',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/73332/M/1876342.jpg',
    },
    {
      label: 'D26 Mandai / Upper Thomson',
      value: 'D26 Mandai / Upper Thomson',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/100411/M/2070071.jpg',
    },
    {
      label: 'D27 Sembawang / Yishun',
      value: 'D27 Sembawang / Yishun',
      images: 'https://s3-ap-southeast-1.amazonaws.com/static.streetsine/Project%20Photos/92301/M/2063261.jpg',
    },
    {
      label: 'D28 Seletar / Yio Chu Kang',
      value: 'D28 Seletar / Yio Chu Kang',
      images:
        'https://esingaporeproperty.sg/wp-content/uploads/2018/03/Parc-Greenwich-Executive-Condo-50M-Pool-675x375.jpeg',
    },
  ],

  condo: [
    { label: 'All Condo Unit Type', value: 'All Condo Unit Type' },
    { label: 'Apartment', value: 'Apartment' },
    { label: 'Cluster House', value: 'Cluster House' },
    { label: 'Condo', value: 'Condo' },
    { label: 'Executive Condo', value: 'Executive Condo' },
    { label: 'Walk-Up', value: 'Walk-Up' },
  ],

  landed: [
    { label: 'All Landed Unit Type', value: 'All Landed Unit Type' },
    { label: 'Bungalow House', value: 'Bungalow House' },
    { label: 'Cluster House', value: 'Cluster House' },
    { label: 'Conservation House', value: 'Conservation House' },
    { label: 'Corner Terrace', value: 'Corner Terrace' },
    { label: 'Detached House', value: 'Detached House' },
    { label: 'Good Class Bungalow', value: 'Good Class Bungalow' },
    { label: 'Land Only', value: 'Land Only' },
    { label: 'Semi-Detached House', value: 'Semi-Detached House' },
    { label: 'Shophouse', value: 'Shophouse' },
    { label: 'Terraced House', value: 'Terraced House' },
    { label: 'Town House', value: 'Town House' },
  ],
  hdbUnit: [
    { label: 'All HDB Unit Type', value: 'All HDB Unit Type' },
    { label: '1 Room/Studio', value: '1 Room/Studio' },
    { label: '2A', value: '2A' },
    { label: '2I (Improved)', value: '2I (Improved)' },
    { label: '2S (Standard)', value: '2S (Standard)' },
    { label: '3A', value: '3A' },
    { label: '3A (Modified)', value: '3A (Modified)' },
    { label: '3I (Improved)', value: '3I (Improved)' },
    { label: '3I (Modified)', value: '3I (Modified)' },
    { label: '3NG (Modified)', value: '3NG (Modified)' },
    { label: '3NG (New Generation)', value: '3NG (New Generation)' },
    { label: '3S (Simplified)', value: '3S (Simplified)' },
    { label: '3STD (Standard)', value: '3STD (Standard)' },
    { label: '4A', value: '4A' },
    { label: '4I (Improved)', value: '4I (Improved)' },
    { label: '4NG (New Generation)', value: '4NG (New Generation)' },
    { label: '4S (Simplified)', value: '4S (Simplified)' },
    { label: '4STD (Standard)', value: '4STD (Standard)' },
    { label: '5A', value: '5A' },
    { label: '5I', value: '5I' },
    { label: '5S', value: '5S' },
    { label: 'Adjoined Flat', value: 'Adjoined Flat' },
    { label: 'EA (Exec Apartment)', value: 'EA (Exec Apartment)' },
    { label: 'EM (Exec Maisonette)', value: 'EM (Exec Maisonette)' },
    { label: 'Jumbo', value: 'Jumbo' },
    { label: 'MG (Multi-Generation)', value: 'MG (Multi-Generation)' },
    { label: 'Model A Maisonette', value: 'Model A Maisonette' },
    { label: 'Premium Apartment', value: 'Premium Apartment' },
    { label: 'Terrace', value: 'Terrace' },
    { label: 'Unknown', value: 'Unknown' },
  ],

  hdbEstate: [
    {
      label: 'Ang Mo Kio',
      value: 'Ang Mo Kio',
    },
    {
      label: 'Bedok',
      value: 'Bedok',
    },
    {
      label: 'Bishan',
      value: 'Bishan',
    },
    {
      label: 'Bukit Batok',
      value: 'Bukit Batok',
    },
    {
      label: 'Bukit Merah',
      value: 'Bukit Merah',
    },
    {
      label: 'Bukit Panjang',
      value: 'Bukit Panjang',
    },
    {
      label: 'Bukit Timah',
      value: 'Bukit Timah',
    },
    {
      label: 'Central Area',
      value: 'Central Area',
    },
    {
      label: 'Choa Chu Kang',
      value: 'Choa Chu Kang',
    },
    {
      label: 'Clementi',
      value: 'Clementi',
    },
    {
      label: 'Geylang',
      value: 'Geylang',
    },
    {
      label: 'Hougang',
      value: 'Hougang',
    },
    {
      label: 'Jurong East',
      value: 'Jurong East',
    },
    {
      label: 'Jurong West',
      value: 'Jurong West',
    },
    {
      label: 'Kallang/Whampoa',
      value: 'Kallang/Whampoa',
    },
    {
      label: 'Lim Chu Kang',
      value: 'Lim Chu Kang',
    },
    {
      label: 'Marine Parade',
      value: 'Marine Parade',
    },
    {
      label: 'Pasir Ris',
      value: 'Pasir Ris',
    },
    {
      label: 'Punggol',
      value: 'Punggol',
    },
    {
      label: 'Queenstown',
      value: 'Queenstown',
    },
    {
      label: 'Sembawang',
      value: 'Sembawang',
    },
    {
      label: 'Sengkang',
      value: 'Sengkang',
    },
    {
      label: 'Serangoon',
      value: 'Serangoon',
    },
    {
      label: 'Simei',
      value: 'Simei',
    },
    {
      label: 'Tampines',
      value: 'Tampines',
    },
    {
      label: 'Toa Payoh',
      value: 'Toa Payoh',
    },
    {
      label: 'Woodlands',
      value: 'Woodlands',
    },
    {
      label: 'Yio Chu Kang',
      value: 'Yio Chu Kang',
    },
    {
      label: 'Yishun',
      value: 'Yishun',
    },
  ],

  property_Type: [
    { value: '44', label: 'Landed' },
    { value: '45', label: 'Condo' },
    { value: '47', label: 'HDB' },
  ],

  landlord: [
    {
      id: 1,
      name: 'Era Network Pte Ltd',
      Address: 'Singapore',
      Email: 'mark@gmail.com',
      phone: '+65-25369369',
    },
  ],
  tenant: [
    {
      id: 1,
      name: 'Mezanur Rahaman',
      Address: 'Bangladesh',
      Email: 'apsis@gmail.com',
      phone: '+8801758366933',
    },
  ],
  propertyAgreement: [
    {
      id: 1,
      name: 'The Venue Residences and Shoppes',
      category: 'Residential',
      subcategory: 'Appartment',
      location: 'singapore',
      price: '2500$',
      floorsize: '1500 SQFT',
      bedroom: '4',
      bathroom: '2',
      build: '2019',
    },
  ],
  form: [
    {
      id: 1,
      bookingCretaeDate: '2022/02/26',
      bookingStartDate: '2022/03/01',
      bookingENdDate: '2022/03/05',
    },
  ],

  currencies: [
    {
      value: ' District',
      label: ' District',
    },
    {
      value: ' Estate',
      label: ' Estate',
    },
    {
      value: ' Unit Type',
      label: ' Unit Type',
    },
    {
      value: 'Leasing Period',
      label: 'Leasing Period',
    },
  ],

  facilitiesOptions: [
    { label: '24 Hour Security', value: '24 Hour Security' },
    { label: 'Badminton Hall', value: 'Badminton Hall' },
    { label: 'Barbeque Area', value: 'Barbeque Area' },
    { label: 'Basketball Court', value: 'Basketball Court' },
    { label: 'Club House', value: 'Club House' },
    { label: 'Community Garden', value: 'Community Garden' },
    { label: 'Covered Car Park', value: 'Covered Car Park' },
    { label: 'Covered Linkways', value: 'Covered Linkways' },
    { label: 'Driving Range', value: 'Driving Range' },
    { label: 'Drop off Point', value: 'Drop off Point' },
    { label: 'Eateries', value: 'Eateries' },
    { label: 'Elderly Wellness', value: 'Elderly Wellness' },
    { label: 'Electrical Substation', value: 'Electrical Substation' },
    { label: 'Fitness Corner', value: 'Fitness Corner' },
    { label: 'Function Room', value: 'Function Room' },
    { label: 'Gymnasium Room', value: 'Gymnasium Room' },
    { label: 'Jacuzzi', value: 'Jacuzzi' },
    { label: 'Jogging Track', value: 'Jogging Track' },
    { label: 'Launderette', value: 'Launderette' },
    { label: 'Library', value: 'Library' },
    { label: 'Meeting Room', value: 'Meeting Room' },
    { label: 'Mini Mart', value: 'Mini Mart' },
    { label: 'Play Ground', value: 'Play Ground' },
    { label: 'Sauna', value: 'Sauna' },
    { label: 'Squash Court', value: 'Squash Court' },
    { label: 'Steam Bath', value: 'Steam Bath' },
    { label: 'Swimming Pool', value: 'Swimming Pool' },
    { label: 'Tennis Courts', value: 'Tennis Courts' },
  ],
  amenitiesOptions: [
    { label: 'Air-Condition', value: 'Air-Condition' },
    { label: 'Balcony', value: 'Balcony' },
    { label: 'Cooker Hob/Hood', value: 'Cooker Hob/Hood' },
    { label: 'Hairdryer', value: 'Hairdryer' },
    { label: 'Garage', value: 'Garage' },
    { label: 'Roof Terrace', value: 'Roof Terrace' },
    { label: 'Intercom', value: 'Intercom' },
    { label: 'Jacuzzi', value: 'Jacuzzi' },
    { label: 'Walk-in Wardrobe', value: 'Walk-in Wardrobe' },
    { label: 'Water Heater', value: 'Water Heater' },
    { label: 'Colonial Building', value: 'Colonial Building' },
    { label: 'Corner Unit', value: 'Corner Unit' },
    { label: 'Maidsroom', value: 'Maidsroom' },
    { label: 'Outdoor Ratio', value: 'Outdoor Ratio' },
    { label: 'Private Garden', value: 'Private Garden' },
    { label: 'Private Pool', value: 'Private Pool' },
    // { label: "Jacuzzi", value: "Jacuzzi" },
    // { label: "Jogging Track", value: "Jogging Track" },
    // { label: "Mini Mart", value: "Mini Mart" },
    // { label: "Library", value: "Library" },
    // { label: "Meeting Room", value: "Meeting Room" },
  ],
  propertyOperatorRole: [
    { id: 'Owner', name: 'Owner' },
    { id: 'Manager', name: 'Manager' },
    { id: 'Guard', name: 'Guard' },
    { id: 'Representative', name: 'Representative' },
  ],
  rentingPeriod: [{ id: 'months', name: 'months' }],
  category: [
    { id: 'Private property', name: 'Private property' },
    { id: 'hdb residential', name: 'HDB Residential' },
    { id: 'Industrial', name: 'Industrial' },
    { id: 'Commercial', name: 'Commercial' },
    { id: 'Residential', name: 'Residential' },
  ],
  months: [
    { id: '1', name: '6 Months' },
    { id: '2', name: '10 Months' },
    { id: '3', name: '15 Months' },
  ],
  subCategory: [
    { id: 'Landed', name: 'Landed' },
    { id: 'Condominiums', name: 'Condominiums' },
    { id: 'Apartments', name: 'Apartments' },
  ],
  rentalSession: [
    { label: '1 Year', value: '1' },
    { label: '2 Years', value: '2' },
    // { label: "3+", value: "3+" },
    // { label: "Short Term", value: "Short Term" },
    // { label: "Flexible", value: "Flexible" },
  ],
  floorLevelOptions: [
    { label: 'Ground', value: 'Ground' },
    { label: 'Low', value: 'Low' },
    { label: 'Mid', value: 'Mid' },
    { label: 'High', value: 'High' },
    { label: 'Penthouse', value: 'Penthouse' },
  ],
  propertyPurpose: [
    { id: 'Rent', name: 'Rent' },
    { id: 'Sell', name: 'Sell' },
  ],
  facingOptions: [
    { label: 'City View', value: 'City View' },
    { label: 'Park View', value: 'Park View' },
    { label: 'Swimming Pool View', value: 'Swimming Pool View' },
    { label: 'Lake View', value: 'Lake View' },
    { label: 'Sea View', value: 'Sea View' },
    { label: 'Other View', value: 'Other View' },
  ],
  othersOptions: [
    { label: 'Air-Con', value: 'Air-Con' },
    { label: 'Cooking', value: 'Cooking' },
    { label: 'Internet', value: 'Internet' },
    { label: 'No Owner Staying', value: 'No Owner Staying' },
    { label: 'PUB Include', value: 'PUB Include' },
    { label: 'Visitors Allowed', value: 'Visitors Allowed' },
  ],
  UnitBedRoom: [
    { label: 'Master Bedroom', value: 'Master Bedroom' },
    { label: 'Bedroom', value: 'Bedroom' },
    { label: 'Shared', value: 'Shared' },
  ],
  UnitBathRoom: [
    { label: 'Shared', value: 'Shared' },
    { label: 'Attached', value: 'Attached' },
  ],
  rental_Type: [
    { value: 'Whole Unit', label: 'Whole Unit' },
    { value: 'Room', label: 'Room' },
  ],
  roomSize: [
    { id: 'Single', name: 'Single' },
    { id: 'Double', name: 'Double' },
    { id: 'More then 2 storeys', name: 'More then 2 Storeys' },
  ],
  rentalType: [
    { label: 'Room rental', value: 'Room Rental' },
    { label: 'Entire Unit', value: 'Entire Unit' },
    { label: 'Single Bed Room', value: 'Single Bed Room' },
    { label: 'Master Bed Room', value: 'Master Bed Room' },
    { label: 'Shared Bed Room', value: 'Shared Bed Room' },
  ],
  unitOption: [
    { label: 'Room rental', value: 'Room Rental' },
    { label: 'Entire Unit', value: 'Entire Unit' },
    { label: 'Single Bed Room', value: 'Single Bed Room' },
    { label: 'Master Bed Room', value: 'Master Bed Room' },
    { label: 'Shared Bed Room', value: 'Shared Bed Room' },
  ],
  bedroomOptions: [
    { label: '1', value: '1' },
    { label: '2', value: '2' },
    { label: '3', value: '3' },
    { label: '4', value: '4' },
    { label: '5+', value: '5+' },
    { label: 'Studio', value: 'Studio' },
  ],
  bathroomOptions: [
    { label: '1', value: '1' },
    { label: '2', value: '2' },
    { label: '3', value: '3' },
    { label: '4', value: '4' },
    { label: '5+', value: '5+' },
  ],
  parking: [
    { id: '0', name: 0 },
    { id: '1', name: 1 },
    { id: '2', name: 2 },
    { id: '3', name: 3 },
    { id: '4', name: 4 },
    { id: '5', name: 5 },
  ],
  buildYear: [
    { id: '1950-1960', name: '1950-1960' },
    { id: '1961-1980', name: '1961-19801' },
    { id: '1981-2000', name: '1981-2000' },
    { id: '2001-2020', name: '2001-2020' },
  ],
  furnishingOptions: [
    { label: 'Unfurnished', value: 'Unfurnished' },
    { label: 'Fully', value: 'Fully' },
    { label: 'Partially', value: 'Partially' },
  ],
  country: [
    { id: 'Singapore', name: 'Singapore' },
    { id: 'Malaysia', name: 'Malaysia' },
    { id: 'Bangladesh', name: 'Bangladesh' },
  ],
  city: [
    { id: 'Dhaka', name: 'Dhaka' },
    { id: 'Khulna', name: 'Khulna' },
    { id: 'Downtown ', name: 'Downtown ' },
  ],

  code: [
    { id: '+65', name: '+65' },
    { id: '+88', name: '+88' },
    { id: '+11 ', name: '+11 ' },
  ],

  local_foreigner: [
    { label: 'Select One', value: '' },
    { label: 'Local', value: 'Local' },
    { label: 'PR', value: 'PR' },
    { label: 'Foreigner (Returning)', value: 'Foreigner (Returning)' },
    { label: 'Foreigner (1st Timer)', value: 'Foreigner (1st Timer)' },
  ],

  cbsList: [
    { label: 'Select One', value: '' },
    { label: 'AA', value: 'AA' },
    { label: 'BB', value: 'BB' },
    { label: 'CC', value: 'CC' },
    { label: 'DD', value: 'DD' },
    { label: 'EE', value: 'EE' },
    { label: 'FF', value: 'FF' },
    { label: 'GG', value: 'GG' },
    { label: 'HH', value: 'HH' },
  ],

  nricTypeList: [
    { label: 'Select One', value: '' },
    { label: 'S', value: 'S' },
    { label: 'T', value: 'T' },
    { label: 'F', value: 'F' },
    { label: 'G', value: 'G' },
    { label: 'M', value: 'M' },
  ],

  genderItems: [
    { value: 'Female', label: 'Female' },
    { value: 'Male', label: 'Male' },
  ],

  ageFactorList: [
    { value: '', label: 'Select One' },
    { value: '<30', label: '<30' },
    { value: '30-35', label: '30-35' },
    { value: '35-55', label: '35-55' },
    { value: '>55', label: '>55' },
  ],

  maritalStatusList: [
    { value: 'Single', label: 'Single' },
    { value: 'Married', label: 'Married' },
    { value: 'Married with Dependant', label: 'Married with Dependant' },
  ],

  representationItems: [
    { value: 'Individual', label: 'Individual' },
    { value: 'Company', label: 'Company' },
  ],

  employmentType: [
    { value: '', label: 'Select One' },
    { value: 'Employed', label: 'Employed' },
    { value: 'Self Employed', label: 'Self Employed' },
    { value: 'Student', label: 'Student' },
  ],

  idTypeListSin: [
    // { value: '', label: 'Select One' },
    { value: 'Dependant Pass', label: 'Dependant Pass' },
    { value: 'Employment Pass', label: 'Employment Pass' },
    { value: 'Long Term Social Visit Pass', label: 'Long Term Social Visit Pass' },
    { value: 'S Pass', label: 'S Pass' },
    { value: 'Student Permit', label: 'Student Permit' },
    { value: 'Work Permit', label: 'Work Permit' },
    { value: 'Not Applicable', label: 'Not Applicable' },
    { value: 'Others', label: 'Others' },
  ],

  nationalityList: [
    // { value: '', label: 'Select One' },
    { value: 'Singapore Citizen', label: 'Singapore Citizen' },
    { value: 'Afghan', label: 'Afghan' },
    { value: 'Albanian', label: 'Albanian' },
    { value: 'Algerian', label: 'Algerian' },
    { value: 'American', label: 'American' },
    { value: 'Andorran', label: 'Andorran' },
    { value: 'Angolan', label: 'Angolan' },
    { value: 'Antiguan', label: 'Antiguan' },
    { value: 'Argentinian', label: 'Argentinian' },
    { value: 'Armenian', label: 'Armenian' },
    { value: 'Australian', label: 'Australian' },
    { value: 'Austrian', label: 'Austrian' },
    { value: 'Azerbaijani', label: 'Azerbaijani' },
    { value: 'Bahamian', label: 'Bahamian' },
    { value: 'Bahraini', label: 'Bahraini' },
    { value: 'Bangladeshi', label: 'Bangladeshi' },
    { value: 'Barbados', label: 'Barbados' },
    { value: 'Belarussian', label: 'Belarussian' },
    { value: 'Belgian', label: 'Belgian' },
    { value: 'Belizean', label: 'Belizean' },
    { value: 'Beninese', label: 'Beninese' },
    { value: 'Bhutanese', label: 'Bhutanese' },
    { value: 'Bolivian', label: 'Bolivian' },
    { value: 'Bosnian', label: 'Bosnian' },
    { value: 'Botswana', label: 'Botswana' },
    { value: 'Brazilian', label: 'Brazilian' },
    { value: 'British', label: 'British' },
    { value: 'British National Overseas', label: 'British National Overseas' },
    { value: 'British Overseas Citizen', label: 'British Overseas Citizen' },
    { value: 'British Overseas Territories Citizen', label: 'British Overseas Territories Citizen' },
    { value: 'British Protected Person', label: 'British Protected Person' },
    { value: 'British Subject', label: 'British Subject' },
    { value: 'Bruneian', label: 'Bruneian' },
    { value: 'Bulgarian', label: 'Bulgarian' },
    { value: 'Burkinabe', label: 'Burkinabe' },
    { value: 'Burundian', label: 'Burundian' },
    { value: 'Cambodian', label: 'Cambodian' },
    { value: 'Cameroonian', label: 'Cameroonian' },
    { value: 'Canadian', label: 'Canadian' },
    { value: 'Cape Verdean', label: 'Cape Verdean' },
    { value: 'Central African Republic', label: 'Central African Republic' },
    { value: 'Chadian', label: 'Chadian' },
    { value: 'Chilean', label: 'Chilean' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Colombian', label: 'Colombian' },
    { value: 'Comoran', label: 'Comoran' },
    { value: 'Congolese', label: 'Congolese' },
    { value: 'Costa Rican', label: 'Costa Rican' },
    { value: 'Croatian', label: 'Croatian' },
    { value: 'Cuban', label: 'Cuban' },
    { value: 'Cypriot', label: 'Cypriot' },
    { value: 'Czech', label: 'Czech' },
    { value: 'D.P.R. Korean', label: 'D.P.R. Korean' },
    { value: 'Danish', label: 'Danish' },
    { value: 'Democratic Republic Of The Congo', label: 'Democratic Republic Of The Congo' },
    { value: 'Djiboutian', label: 'Djiboutian' },
    { value: 'Dominican', label: 'Dominican' },
    { value: 'Dominican (Republic)', label: 'Dominican (Republic)' },
    { value: 'East Timorese', label: 'East Timorese' },
    { value: 'Ecuadorian', label: 'Ecuadorian' },
    { value: 'Egyptian', label: 'Egyptian' },
    { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
    { value: 'Eritrean', label: 'Eritrean' },
    { value: 'Estonian', label: 'Estonian' },
    { value: 'Ethiopian', label: 'Ethiopian' },
    { value: 'Fijian', label: 'Fijian' },
    { value: 'Filipino', label: 'Filipino' },
    { value: 'Finnish', label: 'Finnish' },
    { value: 'French', label: 'French' },
    { value: 'Gabon', label: 'Gabon' },
    { value: 'Gambian', label: 'Gambian' },
    { value: 'Georgian', label: 'Georgian' },
    { value: 'German', label: 'German' },
    { value: 'Ghanaian', label: 'Ghanaian' },
    { value: 'Greek', label: 'Greek' },
    { value: 'Grenadian', label: 'Grenadian' },
    { value: 'Guatemalan', label: 'Guatemalan' },
    { value: 'Guinean', label: 'Guinean' },
    { value: 'Guinean (Bissau)', label: 'Guinean (Bissau)' },
    { value: 'Guyanese', label: 'Guyanese' },
    { value: 'Haitian', label: 'Haitian' },
    { value: 'Honduran', label: 'Honduran' },
    { value: 'Hong Kong', label: 'Hong Kong' },
    { value: 'Hungarian', label: 'Hungarian' },
    { value: 'Icelander', label: 'Icelander' },
    { value: 'Indian', label: 'Indian' },
    { value: 'Indonesian', label: 'Indonesian' },
    { value: 'Iranian', label: 'Iranian' },
    { value: 'Iraqi', label: 'Iraqi' },
    { value: 'Irish', label: 'Irish' },
    { value: 'Israeli', label: 'Israeli' },
    { value: 'Italian', label: 'Italian' },
    { value: 'Ivory Coast', label: 'Ivory Coast' },
    { value: 'Jamaican', label: 'Jamaican' },
    { value: 'Japanese', label: 'Japanese' },
    { value: 'Jordanian', label: 'Jordanian' },
    { value: 'Kazakhstani', label: 'Kazakhstani' },
    { value: 'Kenyan', label: 'Kenyan' },
    { value: 'Kiribati', label: 'Kiribati' },
    { value: 'Kittian & Nevisian', label: 'Kittian & Nevisian' },
    { value: 'Korean, South', label: 'Korean, South' },
    { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
    { value: 'Laotian', label: 'Laotian' },
    { value: 'Latvian', label: 'Latvian' },
    { value: 'Lebanese', label: 'Lebanese' },
    { value: 'Lesotho', label: 'Lesotho' },
    { value: 'Liberian', label: 'Liberian' },
    { value: 'Libyan', label: 'Libyan' },
    { value: 'Liechtensteiner', label: 'Liechtensteiner' },
    { value: 'Lithuanian', label: 'Lithuanian' },
    { value: 'Luxembourger', label: 'Luxembourger' },
    { value: 'Macao', label: 'Macao' },
    { value: 'Macedonian', label: 'Macedonian' },
    { value: 'Madagasy', label: 'Madagasy' },
    { value: 'Malawian', label: 'Malawian' },
    { value: 'Malaysian', label: 'Malaysian' },
    { value: 'Maldivian', label: 'Maldivian' },
    { value: 'Malian', label: 'Malian' },
    { value: 'Maltese', label: 'Maltese' },
    { value: 'Marshallese', label: 'Marshallese' },
    { value: 'Mauritanean', label: 'Mauritanean' },
    { value: 'Mauritian', label: 'Mauritian' },
    { value: 'Mexican', label: 'Mexican' },
    { value: 'Micronesian', label: 'Micronesian' },
    { value: 'Moldavian', label: 'Moldavian' },
    { value: 'Monacan', label: 'Monacan' },
    { value: 'Mongolian', label: 'Mongolian' },
    { value: 'Montenegrin', label: 'Montenegrin' },
    { value: 'Moroccan', label: 'Moroccan' },
    { value: 'Mozambican', label: 'Mozambican' },
    { value: 'Myanmar', label: 'Myanmar' },
    { value: 'Namibian', label: 'Namibian' },
    { value: 'Nauruan', label: 'Nauruan' },
    { value: 'Nepalese', label: 'Nepalese' },
    { value: 'Netherlands', label: 'Netherlands' },
    { value: 'New Zealander', label: 'New Zealander' },
    { value: 'Ni-Vanuatu', label: 'Ni-Vanuatu' },
    { value: 'Nicaraguan', label: 'Nicaraguan' },
    { value: 'Niger', label: 'Niger' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'Norwegian', label: 'Norwegian' },
    { value: 'Omani', label: 'Omani' },
    { value: 'Others', label: 'Others' },
    { value: 'Pakistani', label: 'Pakistani' },
    { value: 'Palauan', label: 'Palauan' },
    { value: 'Palestinian', label: 'Palestinian' },
    { value: 'Panamanian', label: 'Panamanian' },
    { value: 'Papua New Guinean', label: 'Papua New Guinean' },
    { value: 'Paraguayan', label: 'Paraguayan' },
    { value: 'Peruvian', label: 'Peruvian' },
    { value: 'Polish', label: 'Polish' },
    { value: 'Portuguese', label: 'Portuguese' },
    { value: 'Qatari', label: 'Qatari' },
    { value: 'Romanian', label: 'Romanian' },
    { value: 'Russian', label: 'Russian' },
    { value: 'Rwandan', label: 'Rwandan' },
    { value: 'Salvadoran', label: 'Salvadoran' },
    { value: 'Sammarinese', label: 'Sammarinese' },
    { value: 'Samoan', label: 'Samoan' },
    { value: 'Sao Tomean', label: 'Sao Tomean' },
    { value: 'Saudi Arabian', label: 'Saudi Arabian' },
    { value: 'Senegalese', label: 'Senegalese' },
    { value: 'Serbian', label: 'Serbian' },
    { value: 'Seychellois', label: 'Seychellois' },
    { value: 'Sierra Leone', label: 'Sierra Leone' },
    { value: 'Slovak', label: 'Slovak' },
    { value: 'Slovenian', label: 'Slovenian' },
    { value: 'Solomon Islander', label: 'Solomon Islander' },
    { value: 'Somali', label: 'Somali' },
    { value: 'South African', label: 'South African' },
    { value: 'Spanish', label: 'Spanish' },
    { value: 'Sri Lankan', label: 'Sri Lankan' },
    { value: 'St. Lucia', label: 'St. Lucia' },
    { value: 'St. Vincentian', label: 'St. Vincentian' },
    { value: 'Stateless', label: 'Stateless' },
    { value: 'Sudanese', label: 'Sudanese' },
    { value: 'Surinamer', label: 'Surinamer' },
    { value: 'Swazi', label: 'Swazi' },
    { value: 'Swedish', label: 'Swedish' },
    { value: 'Swiss', label: 'Swiss' },
    { value: 'Syrian', label: 'Syrian' },
    { value: 'Taiwanese', label: 'Taiwanese' },
    { value: 'Tajikistani', label: 'Tajikistani' },
    { value: 'Tanzanian', label: 'Tanzanian' },
    { value: 'Thai', label: 'Thai' },
    { value: 'Togolese', label: 'Togolese' },
    { value: 'Tongan', label: 'Tongan' },
    { value: 'Trinidadian & Tobagonian', label: 'Trinidadian & Tobagonian' },
    { value: 'Tunisian', label: 'Tunisian' },
    { value: 'Turk', label: 'Turk' },
    { value: 'Turkmen', label: 'Turkmen' },
    { value: 'Tuvalu', label: 'Tuvalu' },
    { value: 'Ugandan', label: 'Ugandan' },
    { value: 'Ukrainian', label: 'Ukrainian' },
    { value: 'United Arab Emirates', label: 'United Arab Emirates' },
    { value: 'Uruguayan', label: 'Uruguayan' },
    { value: 'Uzbekistan', label: 'Uzbekistan' },
    { value: 'Vatican City State (Holy See)', label: 'Vatican City State (Holy See)' },
    { value: 'Venezuelan', label: 'Venezuelan' },
    { value: 'Vietnamese', label: 'Vietnamese' },
    { value: 'Yemeni', label: 'Yemeni' },
    { value: 'Zambian', label: 'Zambian' },
    { value: 'Zimbabwean', label: 'Zimbabwean' },
    { value: 'Unknown', label: 'Unknown' },
  ],
  raceList: [
    // { value: '', label: 'Select One' },
    { value: 'Achehnese', label: 'Achehnese' },
    { value: 'Afghan', label: 'Afghan' },
    { value: 'African', label: 'African' },
    { value: 'Albanian', label: 'Albanian' },
    { value: 'Ambonese', label: 'Ambonese' },
    { value: 'American', label: 'American' },
    { value: 'Amerindian', label: 'Amerindian' },
    { value: 'Anglo Burmese', label: 'Anglo Burmese' },
    { value: 'Anglo Chinese', label: 'Anglo Chinese' },
    { value: 'Anglo Filipino', label: 'Anglo Filipino' },
    { value: 'Anglo Indian', label: 'Anglo Indian' },
    { value: 'Anglo Saxon', label: 'Anglo Saxon' },
    { value: 'Anglo Thai', label: 'Anglo Thai' },
    { value: 'Annamite', label: 'Annamite' },
    { value: 'Arab', label: 'Arab' },
    { value: 'Armenian', label: 'Armenian' },
    { value: 'Aryan', label: 'Aryan' },
    { value: 'Assami', label: 'Assami' },
    { value: 'Australian', label: 'Australian' },
    { value: 'Austrian', label: 'Austrian' },
    { value: 'Azeri', label: 'Azeri' },
    { value: 'Bajau', label: 'Bajau' },
    { value: 'Balinese', label: 'Balinese' },
    { value: 'Bamar', label: 'Bamar' },
    { value: 'Bangala', label: 'Bangala' },
    { value: 'Bangladeshi', label: 'Bangladeshi' },
    { value: 'Banjarese', label: 'Banjarese' },
    { value: 'Basque', label: 'Basque' },
    { value: 'Batak', label: 'Batak' },
    { value: 'Belgian', label: 'Belgian' },
    { value: 'Bengali', label: 'Bengali' },
    { value: 'Betawi', label: 'Betawi' },
    { value: 'Bhutanese', label: 'Bhutanese' },
    { value: 'Bidayuh', label: 'Bidayuh' },
    { value: 'Bisaya', label: 'Bisaya' },
    { value: 'Bosniak', label: 'Bosniak' },
    { value: 'Boyanese', label: 'Boyanese' },
    { value: 'Brahmin', label: 'Brahmin' },
    { value: 'Brazilian', label: 'Brazilian' },
    { value: 'British', label: 'British' },
    { value: 'Bugis', label: 'Bugis' },
    { value: 'Bulgarian', label: 'Bulgarian' },
    { value: 'Burgher', label: 'Burgher' },
    { value: 'Burmese', label: 'Burmese' },
    { value: 'Butonese', label: 'Butonese' },
    { value: 'Cambodian', label: 'Cambodian' },
    { value: 'Canadian', label: 'Canadian' },
    { value: 'Cape Coloured', label: 'Cape Coloured' },
    { value: 'Caribbean', label: 'Caribbean' },
    { value: 'Caucasian', label: 'Caucasian' },
    { value: 'Ceylon Moor', label: 'Ceylon Moor' },
    { value: 'Ceylonese', label: 'Ceylonese' },
    { value: 'Chamorro', label: 'Chamorro' },
    { value: 'Chinese', label: 'Chinese' },
    { value: 'Cocos', label: 'Cocos' },
    { value: 'Cornish', label: 'Cornish' },
    { value: 'Creole', label: 'Creole' },
    { value: 'Croat', label: 'Croat' },
    { value: 'Czech', label: 'Czech' },
    { value: 'Dane', label: 'Dane' },
    { value: 'Dayak', label: 'Dayak' },
    { value: 'Dusun', label: 'Dusun' },
    { value: 'Dutch', label: 'Dutch' },
    { value: 'Dutch Burgher', label: 'Dutch Burgher' },
    { value: 'Egyptian', label: 'Egyptian' },
    { value: 'English', label: 'English' },
    { value: 'Ethiopian', label: 'Ethiopian' },
    { value: 'Eurasian', label: 'Eurasian' },
    { value: 'Eurasians', label: 'Eurasians' },
    { value: 'European', label: 'European' },
    { value: 'Fijian', label: 'Fijian' },
    { value: 'Filipino', label: 'Filipino' },
    { value: 'Finn', label: 'Finn' },
    { value: 'Flemish', label: 'Flemish' },
    { value: 'French', label: 'French' },
    { value: 'German', label: 'German' },
    { value: 'Ghanaian', label: 'Ghanaian' },
    { value: 'Goan', label: 'Goan' },
    { value: 'Greek', label: 'Greek' },
    { value: 'Gujarati', label: 'Gujarati' },
    { value: 'Gurkha', label: 'Gurkha' },
    { value: 'Haitian', label: 'Haitian' },
    { value: 'Hawaiian', label: 'Hawaiian' },
    { value: 'Hindustani', label: 'Hindustani' },
    { value: 'Hispanic', label: 'Hispanic' },
    { value: 'Hungarian', label: 'Hungarian' },
    { value: 'Iban', label: 'Iban' },
    { value: 'Icelander', label: 'Icelander' },
    { value: 'Indian', label: 'Indian' },
    { value: 'Indians', label: 'Indians' },
    { value: 'Indonesian', label: 'Indonesian' },
    { value: 'Inuit', label: 'Inuit' },
    { value: 'Iranian', label: 'Iranian' },
    { value: 'Iraqi', label: 'Iraqi' },
    { value: 'Irish', label: 'Irish' },
    { value: 'Isoko', label: 'Isoko' },
    { value: 'Israeli', label: 'Israeli' },
    { value: 'Italian', label: 'Italian' },
    { value: 'Jakun', label: 'Jakun' },
    { value: 'Jamaican', label: 'Jamaican' },
    { value: 'Japanese', label: 'Japanese' },
    { value: 'Javanese', label: 'Javanese' },
    { value: 'Jew', label: 'Jew' },
    { value: 'Jordanian', label: 'Jordanian' },
    { value: 'Kachin', label: 'Kachin' },
    { value: 'Kadazan', label: 'Kadazan' },
    { value: 'Kampuchean', label: 'Kampuchean' },
    { value: 'Karen', label: 'Karen' },
    { value: 'Kayah', label: 'Kayah' },
    { value: 'Kayan', label: 'Kayan' },
    { value: 'Kayin', label: 'Kayin' },
    { value: 'Kazakh', label: 'Kazakh' },
    { value: 'Kelabit', label: 'Kelabit' },
    { value: 'Kenyah', label: 'Kenyah' },
    { value: 'Kenyan', label: 'Kenyan' },
    { value: 'Khasi', label: 'Khasi' },
    { value: 'Khmer', label: 'Khmer' },
    { value: 'Kinh', label: 'Kinh' },
    { value: 'Korean', label: 'Korean' },
    { value: 'Kyrgyz', label: 'Kyrgyz' },
    { value: 'Lao', label: 'Lao' },
    { value: 'Latin', label: 'Latin' },
    { value: 'Latvian', label: 'Latvian' },
    { value: 'Lebanese', label: 'Lebanese' },
    { value: 'Libyan', label: 'Libyan' },
    { value: 'Lisu', label: 'Lisu' },
    { value: 'Lithuanian', label: 'Lithuanian' },
    { value: 'Luxembourger', label: 'Luxembourger' },
    { value: 'Madurese', label: 'Madurese' },
    { value: 'Mahratta', label: 'Mahratta' },
    { value: 'Makasarese', label: 'Makasarese' },
    { value: 'Malabari', label: 'Malabari' },
    { value: 'Malagasy', label: 'Malagasy' },
    { value: 'Malay', label: 'Malay' },
    { value: 'Malays', label: 'Malays' },
    { value: 'Malayalee', label: 'Malayalee' },
    { value: 'Maldivian', label: 'Maldivian' },
    { value: 'Maltese', label: 'Maltese' },
    { value: 'Manipuri', label: 'Manipuri' },
    { value: 'Maori', label: 'Maori' },
    { value: 'Marathi', label: 'Marathi' },
    { value: 'Mauritian', label: 'Mauritian' },
    { value: 'Melanau', label: 'Melanau' },
    { value: 'Melanesian', label: 'Melanesian' },
    { value: 'Mestizo', label: 'Mestizo' },
    { value: 'Metis', label: 'Metis' },
    { value: 'Mexican', label: 'Mexican' },
    { value: 'Minangkabau', label: 'Minangkabau' },
    { value: 'Moldavian', label: 'Moldavian' },
    { value: 'Mon', label: 'Mon' },
    { value: 'Mongolian', label: 'Mongolian' },
    { value: 'Moroccan', label: 'Moroccan' },
    { value: 'Murut', label: 'Murut' },
    { value: 'Naga', label: 'Naga' },
    { value: 'Nauruan', label: 'Nauruan' },
    { value: 'Negro', label: 'Negro' },
    { value: 'Nepalese', label: 'Nepalese' },
    { value: 'Netherlander', label: 'Netherlander' },
    { value: 'New Zealander', label: 'New Zealander' },
    { value: 'Newar', label: 'Newar' },
    { value: 'Nigerian', label: 'Nigerian' },
    { value: 'Norwegian', label: 'Norwegian' },
    { value: 'Pakistani', label: 'Pakistani' },
    { value: 'Palestine', label: 'Palestine' },
    { value: 'Parsee', label: 'Parsee' },
    { value: 'Pathan', label: 'Pathan' },
    { value: 'Penan', label: 'Penan' },
    { value: 'Persian', label: 'Persian' },
    { value: 'Peruvian', label: 'Peruvian' },
    { value: 'Pole', label: 'Pole' },
    { value: 'Polish', label: 'Polish' },
    { value: 'Polynesian', label: 'Polynesian' },
    { value: 'Portuguese', label: 'Portuguese' },
    { value: 'Punan', label: 'Punan' },
    { value: 'Punjabi', label: 'Punjabi' },
    { value: 'Rajput', label: 'Rajput' },
    { value: 'Rakhine', label: 'Rakhine' },
    { value: 'Romanian', label: 'Romanian' },
    { value: 'Russian', label: 'Russian' },
    { value: 'Samoan', label: 'Samoan' },
    { value: 'Scot', label: 'Scot' },
    { value: 'Serbia/Montengerin', label: 'Serbia/Montengerin' },
    { value: 'Seychellois', label: 'Seychellois' },
    { value: 'Shan', label: 'Shan' },
    { value: 'Sikh', label: 'Sikh' },
    { value: 'Sindhi', label: 'Sindhi' },
    { value: 'Sinhalese', label: 'Sinhalese' },
    { value: 'Sino Indian', label: 'Sino Indian' },
    { value: 'Sino Japanese', label: 'Sino Japanese' },
    { value: 'Sino Kadazan', label: 'Sino Kadazan' },
    { value: 'Slavic', label: 'Slavic' },
    { value: 'Slovak', label: 'Slovak' },
    { value: 'Somali', label: 'Somali' },
    { value: 'Spanish', label: 'Spanish' },
    { value: 'Sri Lankan', label: 'Sri Lankan' },
    { value: 'Sudanese', label: 'Sudanese' },
    { value: 'Sumatran', label: 'Sumatran' },
    { value: 'Sundanese', label: 'Sundanese' },
    { value: 'Swede', label: 'Swede' },
    { value: 'Swedish', label: 'Swedish' },
    { value: 'Swiss', label: 'Swiss' },
    { value: 'Tajik', label: 'Tajik' },
    { value: 'Tamil', label: 'Tamil' },
    { value: 'Telugu', label: 'Telugu' },
    { value: 'Thai', label: 'Thai' },
    { value: 'Tibetan', label: 'Tibetan' },
    { value: 'Timor', label: 'Timor' },
    { value: 'Tongan', label: 'Tongan' },
    { value: 'Turk', label: 'Turk' },
    { value: 'Turkmen', label: 'Turkmen' },
    { value: 'Ukrainian', label: 'Ukrainian' },
    { value: 'Unknown', label: 'Unknown' },
    { value: 'Uyghur', label: 'Uyghur' },
    { value: 'Uzbek', label: 'Uzbek' },
    { value: 'Venezuelan', label: 'Venezuelan' },
    { value: 'Vietnamese', label: 'Vietnamese' },
    { value: 'Welsh', label: 'Welsh' },
    { value: 'Yugoslav', label: 'Yugoslav' },
    { value: 'Zimbabwean', label: 'Zimbabwean' },
    { value: 'Others', label: 'Others' },
  ],

  bankSavingsRatio: [
    { value: '>20x', label: '>20x' },
    { value: '15-20x', label: '15-20x' },
    { value: '12-15x', label: '12-15x' },
    { value: '10-12x', label: '10-12x' },
    { value: '8-10x', label: '8-10x' },
    { value: '6-8x', label: '6-8x' },
    { value: '4-6x', label: '4-6x' },
    { value: '2-4x', label: '2-4x' },
  ],

  addressType: [
    { value: 'A', label: 'A' },
    { value: 'B', label: 'B' },
    { value: 'C', label: 'C' },
    { value: 'D', label: 'D' },
    { value: 'E', label: 'E' },
    { value: 'F', label: 'F' },
  ],
  educationLevel: [
    { value: '', label: 'Select One' },
    { value: 'PhD', label: 'PhD' },
    { value: 'Masters', label: 'Masters' },
    { value: 'Graduate', label: 'Graduate' },
    { value: 'Polytechnic/ Professional Diploma', label: 'Polytechnic/ Professional Diploma' },
    { value: 'Others', label: 'Others' },
  ],
  salaryRatio: [
    { value: '>5x', label: '>5x' },
    { value: '4-5x', label: '4-5x' },
    { value: '3-4x', label: '3-4x' },
    { value: '2.5-3x', label: '2.5-3x' },
    { value: '2.0-2.5x', label: '2.0-2.5x' },
    { value: '1.5-2x', label: '1.5-2x' },
    { value: '<1.5x', label: '<1.5x' },
  ],
  sector: [
    { value: 'Agri-Technology', label: 'Agri-Technology' },
    { value: 'Construction', label: 'Construction' },
    { value: 'Financial', label: 'Financial' },
    { value: 'Harbourcraft', label: 'Harbourcraft' },
    { value: 'Incinerator Plant', label: 'Incinerator Plant' },
    { value: 'Information Technology', label: 'Information Technology' },
    { value: 'Landscaping', label: 'Landscaping' },
    { value: 'Manufacturing', label: 'Manufacturing' },
    { value: 'Marine', label: 'Marine' },
    { value: 'Medical', label: 'Medical' },
    { value: 'Process', label: 'Process' },
    { value: 'Reclamation', label: 'Reclamation' },
    { value: 'Services', label: 'Services' },
    { value: 'Others', label: 'Others' },
  ],

  relationShipList: [
    { value: 'Main Tenant', label: 'Main Tenant' },
    { value: 'Unrelated', label: 'Unrelated' },
    { value: 'Brother/Sister', label: 'Brother/Sister' },
    { value: 'Brother/Sister-in-law', label: 'Brother/Sister-in-law' },
    { value: 'Cousin', label: 'Cousin' },
    { value: 'Grandparent', label: 'Grandparent' },
    { value: 'Grandparent-in-law', label: 'Grandparent-in-law' },
    { value: 'Grandson/Grandaughter-in-law', label: 'Grandson/Grandaughter-in-law' },
    { value: 'Grandson/daughter', label: 'Grandson/daughter' },
    { value: 'Nephew/Niece', label: 'Nephew/Niece' },
    { value: 'Parent', label: 'Parent' },
    { value: 'Parent-in-law', label: 'Parent-in-law' },
    { value: 'Son/Daughter', label: 'Son/Daughter' },
    { value: 'Son/Daughter-in-law', label: 'Son/Daughter-in-law' },
    { value: 'Spouse', label: 'Spouse' },
    { value: 'Uncle/Aunt', label: 'Uncle/Aunt' },
    { value: 'Uncle/Aunt-in-law', label: 'Uncle/Aunt-in-law' },
  ],

  occup: [
    { id: 'Student', name: 'Student' },
    { id: 'Jobholder', name: 'Jobholder' },
    { id: 'Businessman', name: 'Businessman' },
    { id: 'Others', name: 'Others' },
  ],
  workingArea: [
    { id: 'Administration', name: 'Administration' },
    { id: 'Management Services', name: 'Management Services' },
    { id: 'Finance', name: 'Finance' },
    { id: 'Retail Trade', name: 'Retail Trade' },
    { id: 'Communication', name: 'Communication' },
    { id: 'IT', name: 'IT' },
  ],
  conditionArea: [
    { id: 'Living area', name: 'Living area' },
    { id: 'Dining area', name: 'Dining area' },
    { id: 'Master bedroom', name: 'Master bedroom' },
    { id: 'bedroom #2', name: 'bedroom #2' },
    { id: 'bedroom #3', name: 'bedroom #3' },
    { id: 'Attached bathroom', name: 'Attached bathroom' },
    { id: 'Common toilet', name: 'Common toilet' },
    { id: 'Kitchen', name: 'Kitchen' },
  ],
  condotion: [
    { id: 'stains', name: 'stains' },
    { id: 'holes', name: 'holes' },
    { id: 'cracked plaster', name: 'cracked plaster' },
    { id: 'other damage', name: 'other damage' },
  ],
  employType: [
    { id: 'Selfemployed', name: 'SelfEmployed' },
    { id: 'Student', name: 'Student' },
    { id: 'Employed', name: 'Employed' },
  ],
  representation: [
    { id: 'Individual', name: 'Individual' },
    { id: 'Company', name: 'Company' },
  ],
  bookingOptions: [
    { id: 'student', name: 'Are you a student' },
    { id: 'selfemployed', name: 'Are you self employed' },
    { id: 'employed', name: 'Are you employed' },
  ],
  district: [
    {
      name: 'Singapore',
      lat: '1.3000',
      lng: '103.8000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: 'primary',
      population: '5745000',
      population_proper: '5638700',
      id: 'Singapore',
    },
    {
      name: 'Raffles Place',
      lat: '1.3000',
      lng: '103.8000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: 'primary',
      population: '5745000',
      population_proper: '5638700',
      id: 'Raffles Place',
    },
    {
      name: 'Marina',
      lat: '1.3778',
      lng: '103.7442',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'marina',
    },
    {
      name: 'Cecil',
      lat: '1.3833',
      lng: '103.7500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'cecil',
    },
    {
      name: 'Tanjong Pagar',
      lat: '1.3817',
      lng: '103.7525',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Tanjong',
    },
    {
      name: 'Chinatown',
      lat: '1.3972',
      lng: '103.8719',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Chinatown',
    },
    {
      name: 'Tiong Bahru',
      lat: '1.3956',
      lng: '103.8692',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Tiong',
    },
    {
      name: 'Alexandra',
      lat: '1.3900',
      lng: '103.9072',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Alexandra',
    },
    {
      name: 'Queenstown',
      lat: '1.3819',
      lng: '103.7364',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Queenstown',
    },
    {
      name: 'Mount Faber',
      lat: '1.4456',
      lng: '103.7969',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Mount',
    },
    {
      name: 'Telok Blangah',
      lat: '1.4363',
      lng: '103.7867',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Telok',
    },
    {
      name: 'Harbourfront',
      lat: '1.3811',
      lng: '103.8942',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Harbourfront',
    },
    {
      name: 'Buona Vista',
      lat: '1.3756',
      lng: '103.8972',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Buona',
    },
    {
      name: 'Pasir Panjang',
      lat: '1.3833',
      lng: '103.9000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Pasir',
    },
    {
      name: 'Clementi',
      lat: '1.3900',
      lng: '103.8764',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Clementi',
    },
    {
      name: 'Clarke Quay',
      lat: '1.3786',
      lng: '103.9078',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Clarke',
    },
    {
      name: 'nameHall',
      lat: '.761',
      lng: '039017',
      country: 'Singapore',
      iso2: 'SG',
      admin_nme: 'North East',
      capital: '',
      populaton: '',
      populaton_proper: '',
      id: 'nameHall',
    },
    {
      name: 'Bugis',
      lat: '1.3342',
      lng: '103.7228',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bugis',
    },
    {
      name: 'Beach Road',
      lat: '1.3500',
      lng: '103.7167',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Beach',
    },
    {
      name: 'Golden Mile',
      lat: '1.3844',
      lng: '103.8681',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Golden',
    },
    {
      name: 'Little India',
      lat: '1.4533',
      lng: '103.7989',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Little',
    },
    {
      name: 'Farrer Park',
      lat: '1.3994',
      lng: '103.9028',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Farrer',
    },
    {
      name: 'Orchard Road',
      lat: '1.3808',
      lng: '103.7625',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Orchard',
    },
    {
      name: 'River Valley',
      lat: '1.3814',
      lng: '103.9158',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'River',
    },
    {
      name: 'Bukit Timah',
      lat: '1.4411',
      lng: '103.7708',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bukit',
    },
    {
      name: 'Holland',
      lat: '1.3600',
      lng: '103.8917',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Holland',
    },
    {
      name: 'Balmoral',
      lat: '1.3667',
      lng: '103.8833',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Balmoral',
    },
    {
      name: 'Novena',
      lat: '1.3445',
      lng: '103.7068',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Novena',
    },
    {
      name: 'Newton',
      lat: '1.3333',
      lng: '103.7000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Newton',
    },
    {
      name: 'Thomson',
      lat: '1.3333',
      lng: '103.9333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Thomson',
    },
    {
      name: 'Toa Payoh',
      lat: '1.3333',
      lng: '103.9333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Toa',
    },
    {
      name: 'Serangoon',
      lat: '1.3167',
      lng: '103.9167',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Serangoon',
    },
    {
      name: 'Balestier',
      lat: '1.3236',
      lng: '103.9273',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Balestier',
    },
    {
      name: 'Macpherson',
      lat: '1.3500',
      lng: '103.8833',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Macpherson',
    },
    {
      name: 'Braddell',
      lat: '1.3244',
      lng: '103.9544',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Braddell',
    },
    {
      name: 'Geylang',
      lat: '1.3836',
      lng: '103.7600',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Geylang',
    },
    {
      name: 'Paya Lebar',
      lat: '1.3500',
      lng: '103.8667',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Paya',
    },
    {
      name: 'Joo Chiat',
      lat: '1.4297',
      lng: '103.7675',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Joo',
    },
    {
      name: 'Marina Parade',
      lat: '1.3897',
      lng: '103.8539',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Marina',
    },
    {
      name: 'Yio Chu Kang',
      lat: '1.3911',
      lng: '103.8514',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Yio',
    },
    {
      name: 'Ang Mo Kio',
      lat: '1.3803',
      lng: '103.8397',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Ang',
    },
    {
      name: 'Katong',
      lat: '1.3833',
      lng: '103.8500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Katong',
    },
    {
      name: 'Bedok',
      lat: '1.3792',
      lng: '103.8578',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bedok',
    },
    {
      name: 'Upper East Coast',
      lat: '1.3333',
      lng: '103.9000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Upper',
    },
    {
      name: 'Changi',
      lat: '1.3167',
      lng: '103.9000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Changi',
    },
    {
      name: 'Flora',
      lat: '1.3333',
      lng: '103.9000',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Flora',
    },
    {
      name: 'Loyang',
      lat: '1.3667',
      lng: '103.8667',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Loyang',
    },
    {
      name: 'Pasir Ris',
      lat: '1.3500',
      lng: '103.7500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Pasir',
    },
    {
      name: 'Serangoon Gardens',
      lat: '1.3278',
      lng: '103.8608',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Serangoon',
    },
    {
      name: 'Bishan',
      lat: '1.3833',
      lng: '103.8286',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bishan',
    },
    {
      name: 'Upper Bukit Timah',
      lat: '1.2667',
      lng: '103.8333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Upper',
    },
    {
      name: 'Clementi Park',
      lat: '1.2667',
      lng: '103.8333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Clementi',
    },
    {
      name: 'Tanjong Pagar',
      lat: '1.2833',
      lng: '103.8333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Tanjong',
    },
    {
      name: 'Diary Farm',
      lat: '1.4028',
      lng: '103.8178',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Diary',
    },
    {
      name: 'Choa Chu Kang',
      lat: '1.4033',
      lng: '103.8500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Choa',
    },
    {
      name: 'Bukit Panjang',
      lat: '1.4100',
      lng: '103.8444',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bukit',
    },
    {
      name: 'Kampong Siren',
      lat: '1.3522',
      lng: '103.8981',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Kampong',
    },
    {
      name: 'Springleaf Park',
      lat: '1.3953',
      lng: '103.8214',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Springleaf',
    },
    {
      name: 'Bukit Batok',
      lat: '1.3778',
      lng: '103.9594',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Bukit',
    },
    {
      name: 'Woodlands',
      lat: '1.3881',
      lng: '103.9183',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Woodlands',
    },
    {
      name: 'Admiralty',
      lat: '1.4375',
      lng: '103.8306',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Admiralty',
    },
    {
      name: 'Seletar',
      lat: '1.4381',
      lng: '103.8267',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Seletar',
    },
    {
      name: 'Upper Thomson',
      lat: '1.3944',
      lng: '103.7539',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Upper',
    },
    {
      name: 'Punggol',
      lat: '1.3983',
      lng: '103.9090',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'Central Singapore',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Punggol',
    },
    {
      name: 'Mandai',
      lat: '1.4125',
      lng: '103.9103',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Mandai',
    },
    {
      name: 'Lim Chu Kang',
      lat: '1.4614',
      lng: '103.8364',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Chu',
    },
    {
      name: 'Chong Pang',
      lat: '1.4444',
      lng: '103.8239',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Pang',
    },
    {
      name: 'Sembawang',
      lat: '1.4491',
      lng: '103.8185',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Sembawang',
    },
    {
      name: 'Yishun',
      lat: '1.4333',
      lng: '103.8311',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Yishun',
    },
    {
      name: 'Sarang Rimau',
      lat: '1.2597',
      lng: '103.8089',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Sarang',
    },
    {
      name: 'Tengah',
      lat: '1.3783',
      lng: '103.9319',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'North East',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Tengah',
    },
    {
      name: 'Kranji',
      lat: '1.3517',
      lng: '103.7336',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Kranji',
    },
    {
      name: 'Java Teban',
      lat: '1.3333',
      lng: '103.7333',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Java',
    },
    {
      name: 'Tebing Terjun',
      lat: '1.3333',
      lng: '103.7500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Tebing',
    },
    {
      name: 'Sungai Pandan',
      lat: '1.3167',
      lng: '103.7500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Sungai Pandan',
    },
    {
      name: 'Siglap',
      lat: '1.3167',
      lng: '103.7500',
      country: 'Singapore',
      iso2: 'SG',
      admin_name: 'South West',
      capital: '',
      population: '',
      population_proper: '',
      id: 'Siglap',
    },
  ],
}
